version: '3.8'

services:
  web:
    image: inage-gpj-web:${APP_ENV}
    build:
      context: .
      target: web
    container_name: inage-gpj-web-${APP_ENV}
    networks:
      - gpj_web_network

  nginx:
    image: inage-gpj-nginx:${APP_ENV}
    build:
      context: .
      target: nginx
    container_name: inage-gpj-nginx-${APP_ENV}
    restart: unless-stopped
    ports:
      - ${PORT}:80
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
    depends_on:
      - web   
    networks:
      - gpj_web_network

networks:
  gpj_web_network:
    name: gpj_network
    driver: bridge